#!/usr/bin/bash
#SBATCH -p vertex
#SBATCH -J channel-test
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 10
#SBATCH --cpus-per-task 1
#SBATCH -o output%j.txt
#SBATCH -e error%j.txt
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mxd@ornl.gov
#SBATCH -t 01:00:00

source ~/.vertexcfd-env

export OMP_PROC_BIND=true
export OMP_PLACES=threads

export IOSS_PROPERTIES="COMPOSE_RESULTS=on:MINIMIZE_OPEN_FILES=on:MAXIMUM_NAME_LENGTH=64"
export EXODUS_NETCDF4=1

cd $SLURM_SUBMIT_DIR

exec_path="../bin/vertexcfd"

echo "
SLURM_JOB_ID
$SLURM_JOB_ID

SLURM_JOB_NUM_NODES
$SLURM_JOB_NUM_NODES

SLURM_NTASKS
$SLURM_NTASKS

SLURM_JOB_NODELIST
$SLURM_JOB_NODELIST
"

inputfile=incompressible_2d_channel.xml

mpirun $exec_path --i=$inputfile --kokkos-threads=1
