#include "utils/VertexCFD_Utils_ExplicitTemplateInstantiation.hpp"

#include "VertexCFD_BoundaryState_ElectricPotentialInsulatingWall.hpp"
#include "VertexCFD_BoundaryState_ElectricPotentialInsulatingWall_impl.hpp"

VERTEXCFD_INSTANTIATE_TEMPLATE_CLASS_EVAL_TRAITS(
    VertexCFD::BoundaryCondition::ElectricPotentialInsulatingWall)
